### ISSUE TITLE
SOS constraints are not taken into account if a problem contains only continuous variables

### ISSUE THREAD

**Issue by lovasoa** [KardinalAI/coin_cbc#15]
Due to a bug in cbc, SOS constraints are not taken into account if a problem contains only continuous variables.
See coin-or/Cbc#376.

I implemented a workaround in good_lp, and I thought you might be interested in upstreaming it in this crate: https://github.com/rust-or/good_lp/commit/e64f09f7478968df5c1e95b3663eb9039f135daa

**Comment by TeXitoi** [comment]
Is it fixed in coin cbc 2.10?
