### ISSUE TITLE
Solution::col is very slow

### ISSUE THREAD

**Issue by lovasoa** [KardinalAI/coin_cbc#16]
Hello,
  When using coin_cbc on a large real world problem, I get very poor performance when reading the solution of the problem with `Solution::col`. Reading the values of all the variables in the problem takes 5 times longer than solving the actual problem.
  I believe this is because each time a single variable is extracted, a new slice containing all the variable values is created :  
https://github.com/KardinalAI/coin_cbc/blob/master/src/lib.rs#L328

**Comment by TeXitoi** [comment]
It's not supposed to be expensive. As a workaround, you can `sol.raw().sol()` to get the slice of the solution.

Will try to check.

**Comment by lovasoa** [comment]
> As a workaround, you can `sol.raw().sol()` to get the slice of the solution.

Yes, this is what I implemented as a workaround in good_lp, and collecting the results of my large problem went from taking 5s to being instantaneous.
