### ISSUE TITLE
Input linear program using matrix format

### ISSUE THREAD

**Issue by luli-git** [KardinalAI/coin_cbc#17]
Hi,

I'm trying to use cbc solver to solver some large optimization problems. I have my constraints formatted as Ax=b. However, in all the examples I can find, constraints are added by calling `set_weight` one by one, which does not seem very efficient. Do you know how to format an optimization problem using sparse matrices and vectors without having to add the coefficients one by one? 

Thank you for your help.

**Comment by TeXitoi** [comment]
If you want to do it the hard way, you have access to a minimal safe wrapper to the raw C bindings in the raw module. In particular https://docs.rs/coin_cbc/0.1.5/coin_cbc/raw/struct.Model.html#method.load_problem

Doing this way is order of magnitude more error prone and hard to debug, for a negligeable performance improvement comparing to the cost of solving.

Why do you want to go this way?

Also, note that this is a MILP solver, not a linear solver, so if you want to extract the best performance, that's not the good tool.

**Comment by TeXitoi** [comment]
I solve 100k binary variable problems with the "one weight at a time" interface with not measurable performance overhead.
