### ISSUE TITLE
Cannot Import cbc

### ISSUE THREAD

**Issue by zhli12** [KardinalAI/coin_cbc#18]
Hi,

I would like to use cbc for linear solver, but whenever I tried to import the library using `use coin_cbc::{raw::Status, Col, Model, Sense, Solution as CbcSolution}`, I encountered an error saying `linking with `cc` failed: exit code: 1` with a note starting with `"cc" "-m64" "-arch" "x86_64" "-L"`.

Below is the version information. I'm using a Mac. Thank you for your help!

`
Version: 1.56.2 (Universal)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z (1 wk ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.3.0`

**Comment by TeXitoi** [comment]
This crate just link to a CBC lib, but doesn't provide one. You'll have to install it yourself and let rust find it.

Under Linux, the simplest way is to install it with you distribution package manager. No idea for Mac, and I don't have access to one, so I can't help you on this.
