### ISSUE TITLE
Optimize over Multiple Vectors

### ISSUE THREAD

**Issue by zhli12** [KardinalAI/coin_cbc#20]
Hi,

We have two column vectors to optimize over, say col1 and col2, and one of the constraint involves the their entry by entry difference col1-col2. We used the codes 

`m.set_weight(row,cols[i]-cols2[i] , weight);`

where i is an index, but received an error saying  

"cannot subtract `coin_cbc::Col` from `coin_cbc::Col` " 

It seems that what cols[i] gives is a "Col" object, so we are wondering how to convert it to a value or whether there is another way to optimize over multiple vecotrs. We are doing this because we would like to minimize over the sum of absolute values of each entry (i.e, the L1 norm), so we express x as the difference between two vectors with non-negative entries.

**Comment by TeXitoi** [comment]
Sorry, I missed this.

set_weight just set a weight to a column, it doesn't do any fancy math. So, 

```rust
m.set_weight(row,cols[i], weight);
m.set_weight(row,cols2[i], -weight);
```

if I understand correctly your question.
