### ISSUE TITLE
Question: Move to v2.10?

### ISSUE THREAD

**Issue by alex-ozdemir** [KardinalAI/coin_cbc#22]
Hey folks,

Thanks for creating this library. I use it for a few compiler-related projects.

I'd like to be able to surpress log messages, which requires CBC version 2.10 (see [release notes](https://github.com/coin-or/Cbc)).

Would you be willing to move up to v2.10 if I submit a PR?

Cheers,
Alex

**Comment by TeXitoi** [comment]
Hi!

You can already set the log level: https://github.com/KardinalAI/coin_cbc/issues/3

**Comment by alex-ozdemir** [comment]
Oh, great! Thank you!
