### ISSUE TITLE
pkg-config support for coin_cbc_sys

### ISSUE THREAD

**Issue by Fuuzetsu** [KardinalAI/coin_cbc#23]
It'd be very nice if the code knew how to find the library based on pkg-config information. This allows any tools depending on the crate that understand pkg-config to deal with getting right link flags from pkg-config.

cbc guys already distribute pkg-config files and it's possible to use the very nice `pkg-config` crate to invoke it inside build.rs

**Comment by Fuuzetsu** [comment]
Something as simple as below works for use as a temporary measure.

```diff
diff --git a/coin_cbc_sys/Cargo.toml b/coin_cbc_sys/Cargo.toml
index 61c0953..d434a5e 100644
--- a/coin_cbc_sys/Cargo.toml
+++ b/coin_cbc_sys/Cargo.toml
@@ -9,3 +9,6 @@ repository = "https://github.com/KardinalAI/coin_cbc"
 keywords = ["MILP", "MIP", "linear-programming"]
 categories = ["external-ffi-bindings", "mathematics", "science"]
 license = "MIT "
+
+[build-dependencies]
+pkg-config = "0.3"
\ No newline at end of file
diff --git a/coin_cbc_sys/build.rs b/coin_cbc_sys/build.rs
new file mode 100644
index 0000000..950e687
--- /dev/null
+++ b/coin_cbc_sys/build.rs
@@ -0,0 +1,5 @@
+extern crate pkg_config;
+
+fn main() {
+    let _ = pkg_config::probe_library("cbc");
+}
```

**Comment by TeXitoi** [comment]
As long as it works the same way and only improve cases, I'm open to a PR.
