### ISSUE TITLE
coin_cbc_sys is 0.1.1 on crates.io but only 0.1.0 in repository

### ISSUE THREAD

**Issue by Fuuzetsu** [KardinalAI/coin_cbc#24]
I found out when I tried to patch 0.1.0 for #23 but couldn't find it in the github repo... Seems a bit unusual.

**Comment by TeXitoi** [comment]
Mmm, my repo is also in 0.1.0. I don't know where this 0.1.1 come from.

**Comment by TeXitoi** [comment]
I can't find anything with 0.1.1, so I'll push 0.1.2 with #23

**Comment by TeXitoi** [comment]
coin_cbc_sys v0.1.2 pushed
