### ISSUE TITLE
Odd behaviour for purely linear models

### ISSUE THREAD

**Issue by ARBaart** [KardinalAI/coin_cbc#25]
When a model is purely linear (i.e. all cols are added using ```add_col()```) the solver behaves unexpectedly in two ways, potentially more:
1. The log parameter is not obeyed
2. The (Secondary)Status remains at Unlaunched/Unlaunched, even though the cols do contain the solution

I didn't dive into the source code and perhaps this is to be fixed in the coin_cbc_sys crate, but it seems to me that if the linear relaxation is already the optimal solution, somehow getting to skip the branch&cut phase also means the setting of parameters and updating of the Status is skipped.

**Comment by TeXitoi** [comment]
That's not really a coin_cbc problem, more a problem with CBC itself. CBC is a MILP solver, not as LP solver. It relies on a LP solver behind, and thus using it as a LP solver is not a very good experience.

**Comment by ARBaart** [comment]
A varying mixed integer-linear problem may occasionally have a mix with 0 integer variables. It's perfectly reasonable not to cater specifically to being a great LP solver, but it's dubious behaviour to start ignoring parameters and marking the solution as Unlaunched just because the provided problem instance happens to contain zero integer variables.

**Comment by TeXitoi** [comment]
I agree with you, that's just not what the COIN devs are doing, and I don't want to make any complicated logic to "improve" CBC.
