### ISSUE TITLE
Adjust verbosity level

### ISSUE THREAD

**Issue by carrascomj** [KardinalAI/coin_cbc#3]
Hello!

Would it be possible to adjust the verbosity level like in https://www.coin-or.org/Cbc/ch09.html ? It would be quite convenient but I could not find it in the bindings.

**Comment by TeXitoi** [comment]
```rust
    let mut model = Model::default();
    model.set_parameter("log", "0");
```

There is a lot of parameters available like this. You can search for them using the `cbc` binary, using `?` to have a list, `l?` to have the parameters begining with `l`, and `log??` to have the help of the parameter.

**Comment by carrascomj** [comment]
Ok, that's great. Thank you for the quick reply!

**Comment by TeXitoi** [comment]
welcome!
